name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # dependencies
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
          version: 1.7.0

      - name: goreleaser version
        run: goreleaser -v

      # checkout
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # setup go
      - name: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: go info
        run: |
          go version
          go env

      # cache
      - name: cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # vendor
      - name: vendor
        run: |
          make vendor

      # git status
      - name: git status
        run: git status

      # build
      - name: build
        if: startsWith(github.ref, 'refs/tags/') == false
        run: |
          make snapshot

      # publish
      - name: publish
        if: startsWith(github.ref, 'refs/tags/') == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make publish

      # artifacts
      - name: artifact_linux
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_linux
          path: dist/*linux*

      - name: artifact_darwin
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_darwin
          path: dist/*darwin*

      - name: artifact_windows
        uses: actions/upload-artifact@v2-preview
        with:
          name: build_windows
          path: dist/*windows*